name: Build Arduino Sketch with ZIP Library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Initialize Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli core list
          arduino-cli board listall esp32:esp32


      - name: Compile sketch
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32dev \
            .
